'\" t
.\"  Title: dotload
.\"  Author: [see the "Authors" section]
.\"  Manual: dotload Manual
.\"  Language: English
.\"
.TH "DOTLOAD" "1" "" "" "dotload Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l

.SH NAME
dotload - A simple tool to install dotfiles and other tools

.SH SYNOPSIS
dotload <command> [--branch <branch_name>|-b <branch_name>]

.SH DESCRIPTION
\fBdotload\fR - This is a \fBsimple\fR, \fBintuitive\fR and \fBfast\fR tool for installing configurations (dotfiles) and other necessary tools on any machine!

To learn more, go to the project page - https://github.com/okineadev/dotload

.SH OPTIONS
@username
    This argument specifies the \fIusername\fR of the \fBGitHub\fR user whose dotfiles you want to clone.

--help
    Displays help for commands

--branch, -b branch_name
    This option allows you to specify a particular branch of the dotfiles repository to clone. If not provided, the default branch will be used.

.SH EXIT STATUS
0 - Successful execution
.RE
1 - An error occurred

.SH AUTHOR
\fBOkinea Dev\fR <81070564+okineadev@users.noreply.github.com>

\fBGitHub\fR: https://github.com/okineadev
.RE
\fBTelegram\fR: https://t.me/okinea

.SH BUGS
To report a bug, error or improvement - create an issue on this page: \fBhttps://github.com/okineadev/dotload/issues\fR

.SH NOTES
This man page provides a brief overview of the script's functionalities.
Refer to the script itself for the complete implementation details.
